### ISSUE TITLE
Hook executed successfully but returned HTTP 500

### ISSUE THREAD

**Issue by antonioreyna** [olipo186/Git-Auto-Deploy#106]
when i run the script with `sudo service git-auto-deploy status` i cant get it working but if i run it with:

```
sudo /usr/bin/python /usr/bin/git-auto-deploy --pid-file /var/run/git-auto-deploy/git-auto-deploy.pid --log-file /var/log/git-auto-deploy.log --config /etc/git-auto-deploy.conf.json
```

it works, i added ssh key for root user.

Edit: sorry for the title issues...

**Comment by olipo186** [comment]
HI,

The title ("Hook executed successfully but returned HTTP 500") suggest another issue than the one you are describing in your post. Did GAD perform the deploy while at the same time giving a HTTP 500 response code? That is something I'd need to investigate, but please confirm first if that is the case.

Your other issue is probably related to the fact that GAD runs as a separate user ("git-auto-deploy") meaning that you'll need to copy any ssh keys required to that user's .ssh directory ($HOME/.ssh), which is located at ```/etc/git-auto-deploy/.ssh```. Try copying your ssh keys there and make sure to

    chown -R git-auto-deploy:git-auto-deploy /etc/git-auto-deploy/.ssh

**Comment by olipo186** [comment]
@antonioreyna, please comment here or open another issue if the problem persists.
