### ISSUE TITLE
Can't run bower / composer

### ISSUE THREAD

**Issue by adrianoprospero** [olipo186/Git-Auto-Deploy#108]
My composer and bower are correctly installed on the server. I can execute it manually, but, when I put **bower install** and **composer install** as deploy commands, I get the following errors in log:

2016-06-22 12:49:23,587 [ERROR]  /bin/sh: 1: bower: not found
2016-06-22 12:49:23,587 [ERROR]  /bin/sh: 1: composer: not found

**Comment by DirectorX** [comment]
Which user do you use as the `gad` runner, do you have bower and composer in $PATH?

**Comment by adrianoprospero** [comment]
I use the default user, from the installation (git-auto-deploy).
Both are in /usr/local/bin, that is included in $PATH.

**Comment by olipo186** [comment]
Hi,

I tried to reproduce your issue without luck. Can you try running the same command as the ```git-auto-deploy``` user in a shell?

    sudo su -m git-auto-deploy
    bower --version
    echo $PATH

If you can't get it working, try defining the absolute path to bower (/usr/local/bin/bower) in your config.

**Comment by adrianoprospero** [comment]
Hi,
I already did it (the absolute path thing) and it worked. But about the git-auto-deploy user, I couldn't login or su with it, I don't know why...

Thanks!

**Comment by adrianoprospero** [comment]
@olipo186, 
Now I tried to su git-auto-deploy the way you told (with -m), and got to do it. The path and commands are found. They just don't work when called by Git Auto Deploy. Weird, isn't it?

**Comment by olipo186** [comment]
I agree. It might have something to do with the shell that python invokes, that possibly have some other values in it's $PATH. As I was unable to recreate this I don't have much more to go on. If it happens to more users I might look further into this.
