### ISSUE TITLE
Guide for Debian is out dated

### ISSUE THREAD

**Issue by Fvbor** [olipo186/Git-Auto-Deploy#110]
The Guide for Debian is not longer actual.
In Debian 8.5 it is required to install "apt-get install software-properties-common" to use PPA.

Next problem: 
>Failed to fetch http://ppa.launchpad.net/olipo186/git-auto-deploy/ubuntu/dists/jessie/main/binary->amd64/Packages  404  Not Found

See the complete log here:

>root@debian-512mb-fra1-01:~# apt-get update
>Hit http://security.debian.org jessie/updates InRelease
>Ign http://ppa.launchpad.net jessie InRelease
>Ign http://ppa.launchpad.net jessie Release.gpg
>Ign http://ppa.launchpad.net jessie Release
>Hit http://security.debian.org jessie/updates/main Sources
>Hit http://security.debian.org jessie/updates/main amd64 Packages
>Hit http://security.debian.org jessie/updates/main Translation-en
>Err http://ppa.launchpad.net jessie/main amd64 Packages
>  404  Not Found
>Ign http://mirrors.digitalocean.com jessie InRelease
>Ign http://ppa.launchpad.net jessie/main Translation-en_US
>Get:1 http://mirrors.digitalocean.com jessie-updates InRelease [142 kB]
>Ign http://ppa.launchpad.net jessie/main Translation-en
>Hit http://mirrors.digitalocean.com jessie Release.gpg
>Hit http://mirrors.digitalocean.com jessie Release
>Get:2 http://mirrors.digitalocean.com jessie-updates/main Sources [15.4 kB]
>Get:3 http://mirrors.digitalocean.com jessie-updates/main amd64 Packages/DiffIndex [4,456 B]
>Get:4 http://mirrors.digitalocean.com jessie-updates/main Translation-en/DiffIndex [2,704 B]
>Hit http://mirrors.digitalocean.com jessie/main Sources
>Hit http://mirrors.digitalocean.com jessie/main amd64 Packages
>Hit http://mirrors.digitalocean.com jessie/main Translation-en
>Fetched 165 kB in 3s (46.2 kB/s)
>W: Failed to fetch http://ppa.launchpad.net/olipo186/git-auto-deploy/ubuntu/dists/jessie/main/binary->amd64/Packages  404  Not Found
>
>E: Some index files failed to download. They have been ignored, or old ones used instead.
>root@debian-512mb-fra1-01:~# apt-get install git-auto-deploy
>Reading package lists... Done
>Building dependency tree
>Reading state information... Done
>E: Unable to locate package git-auto-deploy
>root@debian-512mb-fra1-01:~#

**Comment by olipo186** [comment]
Hi,

Thank you for the info. I've added a line in the instructions about the software-properties-common package. It seems like the install instructions are in fact targeted against ubuntu more than debian in general, since the packages provided though our PPA are built for ubuntu.

You can however, with a small tweak, install any of the ubuntu packages on your debian system. I found this post that covers it; http://unix.stackexchange.com/questions/248367/how-to-install-ppas-from-launchpad-on-non-ubuntu-distros-like-debian

You'll need to make an edit in the relevant file in ```/etc/apt/sources.list.d/``` and make apt fetch the GAD package for one of the supported ubuntu versions instead (```xenial``` for example). Please let me know how it works out! If it works, I'll make an update in the instructions for this as well.

**Comment by Fvbor** [comment]
Hello olipo,

a few seconds ago I tested the configuration for debian.
It works!

I looking forward for a new doc ;)

Thanks

**Comment by olipo186** [comment]
Glad to hear!

Did the init script work as well? GAD starts automatically on boot?

Also, can I ask you of the filename of the file you needed to edit in ```/etc/apt/sources.list.d/```? I can then include the same in the instructions.

**Comment by Fvbor** [comment]
So the file is named:
/etc/apt/sources.list.d/olipo186-git-auto-deploy-jessie.list

Regarding the init script: I´ll try it tomorrow and give you an update.

**Comment by Fvbor** [comment]
Hi olipo,

hm... I can not say if it works. In the Log are few errors.

>root@debian-512mb-fra1-01:~# service git-auto-deploy status
>● git-auto-deploy.service - LSB: Script to start Autodeploy Git
>   Loaded: loaded (/etc/init.d/git-auto-deploy)
>   Active: active (exited) since Wed 2016-06-29 16:01:36 EDT; 10min ago
>  Process: 485 ExecStart=/etc/init.d/git-auto-deploy start (code=exited, status=0/SUCCESS)


Reboot:
>2016-06-29 16:01:22,857 [INFO ]  Goodbye

Maybe you can say something 

> root@debian-512mb-fra1-01:~# less /var/log/git-auto-deploy.log
>2016-06-29 15:49:43,329 [INFO ]  Repository https://github.com/olipo186/Git-Auto-Deploy.git not present and needs to be cloned
>2016-06-29 15:49:43,334 [ERROR]  /bin/sh: 1: git: not found
>2016-06-29 15:49:43,334 [ERROR]  Unable to clone master branch of repository https://github.com/olipo186/Git-Auto-Deploy.git
>2016-06-29 15:49:43,334 [INFO ]  Repository https://github.com/github/gitignore not present and needs to be cloned
>2016-06-29 15:49:43,336 [ERROR]  /bin/sh: 1: git: not found
>2016-06-29 15:49:43,336 [ERROR]  Unable to clone master branch of repository https://github.com/github/gitignore
>2016-06-29 15:49:43,336 [INFO ]  Starting Git Auto Deploy in daemon mode
>2016-06-29 15:49:43,344 [DEBUG]  Successfully cleared lock: /var/lib/git-auto-deploy/Git-Auto-Deploy/status_running
>2016-06-29 15:49:43,344 [DEBUG]  Successfully cleared lock: /var/lib/git-auto-deploy/Git-Auto-Deploy/status_waiting
>2016-06-29 15:49:43,344 [DEBUG]  Successfully cleared lock: /var/lib/git-auto-deploy/gitignore/status_running
>2016-06-29 15:49:43,345 [DEBUG]  Successfully cleared lock: /var/lib/git-auto-deploy/gitignore/status_waiting
>2016-06-29 15:49:43,347 [INFO ]  Listening on 0.0.0.0 port 8001
>2016-06-29 16:01:22,857 [INFO ]  Requested close by SIGABRT (process abort signal). Code 6.
>2016-06-29 16:01:22,857 [INFO ]  Goodbye
>2016-06-29 16:01:36,827 [INFO ]  Repository https://github.com/olipo186/Git-Auto-Deploy.git not present and needs to be cloned
>2016-06-29 16:01:36,834 [ERROR]  /bin/sh: 1: git: not found
>2016-06-29 16:01:36,835 [ERROR]  Unable to clone master branch of repository https://github.com/olipo186/Git-Auto-Deploy.git
>2016-06-29 16:01:36,835 [INFO ]  Repository https://github.com/github/gitignore not present and needs to be cloned
>2016-06-29 16:01:36,841 [ERROR]  /bin/sh: 1: git: not found
>2016-06-29 16:01:36,841 [ERROR]  Unable to clone master branch of repository https://github.com/github/gitignore
>2016-06-29 16:01:36,842 [INFO ]  Starting Git Auto Deploy in daemon mode
>2016-06-29 16:01:36,846 [ERROR]  Traceback (most recent call last):
>2016-06-29 16:01:36,846 [ERROR]  File "/usr/bin/git-auto-deploy", line 9, in <module>
>2016-06-29 16:01:36,846 [ERROR]
>2016-06-29 16:01:36,846 [ERROR]  load_entry_point('git-auto-deploy==0.3', 'console_scripts', 'git-auto-deploy')()
>2016-06-29 16:01:36,846 [ERROR]  File "/usr/lib/python2.7/dist-packages/gitautodeploy/gitautodeploy.py", line 470, in main
>2016-06-29 16:01:36,846 [ERROR]
>2016-06-29 16:01:36,846 [ERROR]  app.setup(config)
>2016-06-29 16:01:36,846 [ERROR]  File "/usr/lib/python2.7/dist-packages/gitautodeploy/gitautodeploy.py", line 310, in setup
>2016-06-29 16:01:36,847 [ERROR]
>2016-06-29 16:01:36,847 [ERROR]  self.create_pid_file()
>2016-06-29 16:01:36,847 [ERROR]  File "/usr/lib/python2.7/dist-packages/gitautodeploy/gitautodeploy.py", line 175, in create_pid_file
>2016-06-29 16:01:36,847 [ERROR]
>2016-06-29 16:01:36,847 [ERROR]  with open(self._config['pidfilepath'], 'w') as f:
>2016-06-29 16:01:36,847 [ERROR]  IOError
>2016-06-29 16:01:36,847 [ERROR]  :
>2016-06-29 16:01:36,847 [ERROR]  [Errno 13] Permission denied: '/var/run/git-auto-deploy/git-auto-deploy.pid'
>2016-06-29 16:01:36,847 [ERROR]
>/var/log/git-auto-deploy.log (END)


Maybe you see something in this log.

Thanks
Have a nice day

**Comment by olipo186** [comment]
There seems to be a problem with your $PATH, since you get

    2016-06-29 16:01:36,834 [ERROR] /bin/sh: 1: git: not found

I've created a new issue (https://github.com/olipo186/Git-Auto-Deploy/issues/117) that covers the implementation of a new config option to manually set the path for the git executable. Such a feature would help in this case.

**Comment by olipo186** [comment]
Closing this in favour of #117.
