### ISSUE TITLE
Feature for adding secret token

### ISSUE THREAD

**Issue by vinhtq** [olipo186/Git-Auto-Deploy#114]
I think we should check the token before we continue to pull the source code right?

Imagine they know the ip, they can mess up our repo on server right?

**Comment by olipo186** [comment]
There is such a feature: https://github.com/olipo186/Git-Auto-Deploy/blob/master/docs/Configuration.md#repositories

**secret-token**: The secret token set for your webhook (currently only implemented for GitHub and GitLab)

Have you tried it?

**Comment by olipo186** [comment]
Closing this. Please reopen if something is unclear.

**Comment by vinhtq** [comment]
Ah ok, sorry for not find out this. Thank you!
