### ISSUE TITLE
ssh key problem

### ISSUE THREAD

**Issue by realsby** [olipo186/Git-Auto-Deploy#121]
I created ssh key as root then copied /etc/gap ... Then i changed permissions and ownerships ... Then i add key to the origin git repo host.

But still getting this error. Am i missing anything?

[ERROR]  Load key "/etc/git-auto-deploy/.ssh/id_rsa": Permission denied
[ERROR]  Permission denied (publickey).
[ERROR]  fatal: Could not read from remote repository.

**Comment by olipo186** [comment]
[ERROR] Load key "/etc/git-auto-deploy/.ssh/id_rsa": Permission denied

It looks like you have the wrong file permissions on your keys. Try fixing them with chown and chmod.
