### ISSUE TITLE
Messes up permissions

### ISSUE THREAD

**Issue by danieltcv** [olipo186/Git-Auto-Deploy#123]
Upon cloning it messes up permissions for some reason - the world are all ---

**Comment by danieltcv** [comment]
I believe I found the problem, at least for Ubuntu. The init script at /etc/init.d/git-auto-deploy is setting a default umask of 0027:

```
 75         start-stop-daemon --start --quiet --pidfile $PIDFILE --startas $DAEMON \
 76                 --name $NAME --umask 0027 --chuid $DAEMON_UID:$DAEMON_GID -- $OPTIONS \
```

I believe this should be the normal 002. Is there any particular reason for the restricted permission?

**Comment by olipo186** [comment]
Hi!

I think actually that umask 0027 is a good default. It's restrictive but makes GAD "secure by default" in this case.

Instead of changing the umask, you could add the user that needs to have access to the repositories to the git-auto-deploy group.
