### ISSUE TITLE
Can support other git repo management service, except for github/gitlab/bitbucket?

### ISSUE THREAD

**Issue by xohozu** [olipo186/Git-Auto-Deploy#124]
Sometimes, someone do not use any of the very popular git services like github/gitlab/bitbucket, but that he used is also providing webhook which using specific payload format.   
So, whether `Git-Auto-Deploy` can provide a simple way to customize our special git service so that he can drop it to use in little minutes.   
Certainly, I can derive a custom class from `WebhookRequestParser` to do my own staff and modify every place I need.

**Comment by olipo186** [comment]
Hi,

Currently, the best way is to derive a custom class from WebhookRequestParser for the git service in question. Did you have any particular git service in mind?

Best regards,
Oliver

**Comment by xohozu** [comment]
Yes, I have implemented a custom subclass of `WebhookRequestParser` for [Coding](https://coding.net) service (popular in China).
However, derive a custom class is a efficient way to achieve it. It is not an out of the box way.

**Comment by olipo186** [comment]
Very nice! Please [make a PR](https://help.github.com/articles/creating-a-pull-request/) with your addition. After that, it will be "out of the box".
