### ISSUE TITLE
After reboot server, why it cant create pid file :S

### ISSUE THREAD

**Issue by realsby** [olipo186/Git-Auto-Deploy#125]
/gitautodeploy.py", line 175, in create_pid_file

IOError

Permission denied:

**Comment by smmsadrnezh** [comment]
Same here.
After a reboot when I run `service git-auto-deploy` It failed to start and I got this error in my log files:

> with open(self._config['pidfilepath'], 'w') as f:
> IOError
> :
> [Errno 13] Permission denied: '/var/run/git-auto-deploy/git-auto-deploy.pid'

**Comment by olipo186** [comment]
Probably related to https://github.com/olipo186/Git-Auto-Deploy/issues/122. I'll look into it.

**Comment by olipo186** [comment]
Fixed and released in version 0.4 👍
