### ISSUE TITLE
deploy command

### ISSUE THREAD

**Issue by mhipo1364** [olipo186/Git-Auto-Deploy#127]
Hi

I have an `angular` project, I manage my static files via `grunt` task runner, I want to execute `grunt` command after `pulling`,  so I add `grunt` in `deploy` option but I got this error:

    /bin/sh: 1: grunt: not found

I change `grunt` with `/usr/local/bin/grunt`, now I did not get any error but grunt not run !!!

**Comment by olipo186** [comment]
Hi,

This sounds very much like a problem related to your environment. Probably something wrong with the ```PATH``` environment variable for the user that is running ```GAD```.
