### ISSUE TITLE
How to get it work on GitLab 8.10.2?

### ISSUE THREAD

**Issue by wingliu0** [olipo186/Git-Auto-Deploy#128]
As I'm using CentOS, I downloaded the project to my ~ manually, and I ran your script with the below config
`{
  "pidfilepath": "~/.gitautodeploy.pid",
  "logfilepath": "~/gitautodeploy.log",
  "host": "0.0.0.0",
  "port": 50001,
  "global_deploy": [
    "echo Deploy started!",
    "echo Deploy completed!"
  ],
  "repositories": [
    {
      "url": "THE_HTTP_URL_COPIED_FROM_MY_PROJECT_ON_GITLAB",
      "path": "ABSOLUTE_PATH_TO_MY_PROJECT_ON_SERVER",
      "deploying": "echo deploying"
    }
  ]
}`
It started with log `2016-07-31 06:22:41,187 [INFO ]  Listening on 0.0.0.0 port 50001`
But the webhook on gitLab does not work, It said 

> Hook execution failed: execution expired

How should I config the webhook on gitLab?

**Comment by olipo186** [comment]
Hi,

This looks and sounds like a configuration or network error. Maybe your machine is not publicly availably on the webhook address (firewall etc).

**Comment by montrealist** [comment]
For anyone who finds this, solved it on a Digital Ocean server by opening up the port in the firewall:

`sudo ufw allow 8866/tcp`

Port should be the same as in the `git-auto-deploy.conf.json`. To test, you can run `telnet yourserver.com 8866` and get a response like this (or use the 'test' button in Gitlab UI):

```
Trying XXX.XXX.XX.XX...
Connected to yourserver.com.
Escape character is '^]'.
```
