### ISSUE TITLE
PPA repository and PID file.

### ISSUE THREAD

**Issue by jstnmthw** [olipo186/Git-Auto-Deploy#132]
I installed Git-Auto-Deploy repository via apt-get on Ubuntu 14.04.4 LTS.  I changed my PID location because permissions prevent a user other than root to create files inside /var/run (GAD uses the user git-auto-deploy). It seems the program is stil looking for the PID file in the default location (/var/run) and thus not showing the status or being able to stop the program.

> No process in pidfile '/var/run/git-auto-deploy.pid' found running; none killed.
> /usr/bin/git-auto-deploy is not running

My config:
```{
  "pidfilepath": "~/.git-auto-deploy.pid",
  "logfilepath": "/var/log/git-auto-deploy.log",
  "host": "0.0.0.0",
  "port": 8080,
  "global_deploy": [
    "echo Deploy started!",
    "echo Deploy completed!"
  ],
}```

The process runs and deploys fine but another error I get in the log is:

> [CRITI]  Error on socket: [Errno 98] Address already in use


But on `netstat -tulpn` I have only one process listening and it's the GAD program

> tcp        0      0 0.0.0.0:8080            0.0.0.0:*               LISTEN      1460/python


Lasty, I get a GIT error that doesn't seem to effect anything

> [ERROR]  Reset branch 'master'

With all this said, the program does deploy fine.

**Comment by jstnmthw** [comment]
Ok, so I was right about the program looking for the wrong location of the PID file. I noticed you changed the Debian init script to read directly from "/var/run" from it reading inside a folder "/var/run/git-auto-deploy". I set that location back to read from the git-auto-deploy folder and now it creates and reads the PID file correctly. 

Seems the port in use is gone as well.

I am still getting the following error:
`[ERROR] Reset branch 'master'`

I went in a reset my branch manually but the error still popping up. Any thoughts?

**Comment by olipo186** [comment]
Hi,

Thanks for the feedback. I thought I had solved the pid issue in the most recent update 2 days ago, but I'll have to look into it again. As you also discovered, the problem originates from a bad assumption that /var/run/git-auto-deploy directory will remain intact after a reboot.

The fact that the output from Git is tagged as "ERROR" is also a bug, even if it's cosmetic.

The document you read refers to the init script here: https://github.com/olipo186/Git-Auto-Deploy/blob/master/platforms/linux/initfiles/debianLSBInitScripts/git-auto-deploy which actually runs as root. The init script you are using is a different one. The script bundled with the debian packages is configured to run as the user git-auto-deploy.

**Comment by jstnmthw** [comment]
Ahh, ok gotcha. I guess it was a little confusing cause they're both quite close in relation. I didn't see any README's for the Debian repos. 

Good to know the Git error is nothing also.
