### ISSUE TITLE
Can't run BOWER or NPM

### ISSUE THREAD

**Issue by SteveyPugs** [olipo186/Git-Auto-Deploy#133]
OS: Windows 2K8 R2

I have been trying to run NPM and BOWER commands to do installs automatically on completion of the pull. I get **'"npm install"' is not recognized as an internal or external command**. I do have the items in my system variables. Just a note in my config file below the OS is in C, but our websites are on D as we don't keep the OS and Sites on the same drive. I have tried it with the sites being on the C drive with the same result.

``` json
{
    "pidfilepath": "~/.gitautodeploy.pid",
    "logfilepath": "~/gitautodeploy.log",
    "host": "IP",
    "port": 80,
    "log-level": "INFO",    
    "repositories": [{
        "url": "git@repo.git",
        "branch": "develop",
        "remote": "origin",
        "path": "D:/test",
        "deploy": "npm install"
    }]
}
```

Let me know if I can provide any more detail

**Comment by olipo186** [comment]
Hi,

It sounds like a problem with your PATH variable, not your GAD config. Make sure that your commands (```npm``` and ```bower```) works as expected in cmd prompts, then they should work when invoked from the script as well.

**Comment by SteveyPugs** [comment]
@olipo186 they work perfectly fine with cmd, never had an ssue with them on the D or C drive. Could it be that CMD is doing it from administrator mode?

**Comment by SteveyPugs** [comment]
Just also go confirm you mean the system variables "path" in environments correct?

**Comment by olipo186** [comment]
Yes, that's the one: ![windows-7-user-environment-variables](https://cloud.githubusercontent.com/assets/1056476/18224622/9ca35c0a-71dc-11e6-9818-b986ba5f4a59.gif)

How are you starting GAD? Manually in a cmd prompt (python gitautodeploy), using a windows service or something else?

**Comment by SteveyPugs** [comment]
Manually right now, I haven't gone down the service path yet.

**Comment by SteveyPugs** [comment]
@olipo186 Any news on my comment above?

**Comment by SteveyPugs** [comment]
@olipo186 is it possible because of my code being on a separate drive then where NPM or bower is?

**Comment by SteveyPugs** [comment]
One thing I noticed is the wrapper is putting quotes around my process

**Comment by SteveyPugs** [comment]
@olipo186 I think that's issue, anytime I do a command in deploy that more than one word it does not handle it well

For example, if I do this it works fine

```
npm
```

If I do this it does not:

```
npm install
```

**Comment by SteveyPugs** [comment]
It's definitely something to do with windows handling of unicode
