### ISSUE TITLE
webhook timeout 

### ISSUE THREAD

**Issue by richhl** [olipo186/Git-Auto-Deploy#134]
How can I avoid this? i want to execute a local script that takes it time to execute and got always timeout

![timeouts](https://cloud.githubusercontent.com/assets/1074446/18394040/3f75eb16-76b8-11e6-93a0-d87c8b8f8462.png)

I have tried to put my script in background in config.json with this conf but without success as timeout still happens:

```
  "repositories": [
    {
      "url": "git@bitbucket.org:richhl/myrepo.git",
      "branch": "develop", 
      "remote": "origin", 
      "path": "~/repositories/myrepo/develop",
      "deploy": "nohup ~/repositories/myrepo/deploy.sh > ~/deployscript.log &"
    }, 
```

**Comment by realsby** [comment]
I think you should add detailed-response.. Let me know is it work for you.

 "repositories": [
    {
      "url": "git@bitbucket.org:richhl/myrepo.git",
      "branch": "develop", 
      "remote": "origin", 
      "path": "~/repositories/myrepo/develop",
      "detailed-response": "False",
      "deploy": "nohup ~/repositories/myrepo/deploy.sh > ~/deployscript.log &"
    },

**Comment by olipo186** [comment]
Hi @richhl ,

The config option suggested by @realsby should work. Since version 0.5 this is also the default behavior. Reopen the issue in case the problem remains.
