### ISSUE TITLE
Config change doesnt get reloaded

### ISSUE THREAD

**Issue by patrickhaug** [olipo186/Git-Auto-Deploy#140]
When i change the config and restart the service, it appears to load the old config file. 

Some ideas?

**Comment by realsby** [comment]
Make sure you edited right file.. This never happened to me so far..

vim /etc/git-auto-deploy.conf.json
service git-auto-deploy restart

**Comment by olipo186** [comment]
I agree with @realsby, make sure you're editing the correct file. Reopen if it persists.
