### ISSUE TITLE
Can't get filter to work (Gitlab)

### ISSUE THREAD

**Issue by vcorreze** [olipo186/Git-Auto-Deploy#142]
Hi,

I installed git-auto-deploy over my production server (Debian 7.11) via read-only pull from repo (on a gitlab-ce 8.12.7-ce.0).

I have 2 repositories. 
- The first one is html and is configured with a push filter on `refs/heads/master` and works fine.
- The second is php, and has a pipeline for tests. I want to configure it with update only on succesful build or pipeline (with a manual dummy deploy task at the end of the pipeline in gitlab).

Whatever I put in the filter section for the second one, I am ansvered `filter '*_status'' does not match since the path is invalid`

I've tried build_status, status, pipeline_status, no match ever. If I go with the push filter, everything goes fine.

Here are the config parts : 
_This works_: 

``` json
"filters": [
{
  "object_kind":"push",
  "ref": "refs/heads/master"
}
]
```

_This doesn't_:

``` json
"filters": [
{
  "object_kind":"pipeline",
  "ref": "master",
  "pipeline_status": "success"
}
]
```

This neither :

``` json
"filters": [
{
  "object_kind":"pipeline",
  "ref": "refs/heads/master",
  "pipeline_status": "success"
}
]
```

This neither : 

``` json
"filters": [
{
  "object_kind":"pipeline",
  "ref": "master",
  "status": "success"
}
]
```

Nor this (**copied from doc**, full repository params showed) :

``` json
"url": "https://user:pwd@server/name/projetct.git",
"branch": "master",
"remote": "origin",
"path": "/var/www/myproject",
"secret-token": "myToken",
"filters": [
  {
    "object_kind":"build",
    "ref": "master",
    "build_status": "success"
  }
]
```

I always get the same return `Filter 'build_status'' does not match since the path is invalid`. (by the way, there's a typo in the response : 2 simple quote at the end of the message).

What do I miss ?

**Comment by realsby** [comment]
I need this too..

**Comment by olipo186** [comment]
Hi,

Do you think you could get a copy of the HTTP request being sent to your GAD instance from your git server?

There is a feature built in to GAD for collecting incoming HTTP requests for testing purposes. By adding the following two lines in your config, you can store copies of incoming HTTP requests;

```
  "log-test-case": true,
  "log-test-case-dir": "/path/to/gad/samples/dir",
```

Please post a copy of the HTTP request (with any sensitive data such as IP or username left out), then I can have a look at why the filter fails.

BR,
Oliver
