### ISSUE TITLE
How I can run server in non-daemon mode?

### ISSUE THREAD

**Issue by besir** [olipo186/Git-Auto-Deploy#145]
Hello,
if I run deploy server as service on Ubuntu, i need run it in non-daemon mode. Docker need running script and if i run tailf on end of entrypoint then i don't see any output from GAD. THX!

**Comment by olipo186** [comment]
Sorry I don't understand your issue. You can run GAD in non-daemon mode, for example like this https://github.com/olipo186/Git-Auto-Deploy/blob/master/docs/Install%20as%20a%20python%20module.md Reopen and detail the issue a bit more if it remains.

**Comment by besir** [comment]
My problem is simple, I need run GAD in non-daemon mode.

My install way of GAD:
```
add-apt-repository ppa:olipo186/git-auto-deploy
apt-get update
apt-get install  -y git-auto-deploy
```

And I run it:
`service git-auto-deploy start --port 8080`

but! 

Your Ubuntu package is running force with daemon mode https://github.com/olipo186/Git-Auto-Deploy/blob/master/platforms/debian/stdeb/git-auto-deploy.init#L24 , but I need for Docker run it in standard "non-daemon" mode. I need see output of script in stdout etc.
