### ISSUE TITLE
 X-Gitlab-Token verify not implementation

### ISSUE THREAD

**Issue by ihipop** [olipo186/Git-Auto-Deploy#146]
gitlab webhook has a `Secret Token`, It will be sent with the request in the X-Gitlab-Token HTTP header.
but i did‘nt see any `Secret Token` verify in https://github.com/olipo186/Git-Auto-Deploy/blob/master/gitautodeploy/parsers/gitlab.py

**Comment by olipo186** [comment]
Fixed in https://github.com/olipo186/Git-Auto-Deploy/commit/c98d5b22de7bed03c6345775539a405e61e58477 and released in version 0.7 of the deb package
