### ISSUE TITLE
Documentation Typo: docs/Configuration.md

### ISSUE THREAD

**Issue by MrPlumbum82** [olipo186/Git-Auto-Deploy#166]
Minor typo detected in the documentation. In the first paragraph of the file docs/Configuration.md there is a misspelled word. 

> Every command line option has also a corresponding environemnt variable.

_environemnt_ should be _environment_.

And I want to say I'm a huge fan of this project. Kudos to the developers! :+1:

**Comment by olipo186** [comment]
Thanks for the info!
