### ISSUE TITLE
[Git-Auto-Deploy V0.2.5] AttributeError: 'module' object has no attribute 'NullHandler

### ISSUE THREAD

**Issue by drsaluml** [olipo186/Git-Auto-Deploy#169]
`/usr/bin/python /home/Git-Auto-Deploy/gitautodeploy --daemon-mode --quiet --config /home/Git-Auto-Deploy/config.json`

`
Traceback (most recent call last):
  File "/usr/lib64/python2.6/runpy.py", line 122, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib64/python2.6/runpy.py", line 34, in _run_code
    exec code in run_globals
  File "/home/Git-Auto-Deploy/gitautodeploy/__main__.py", line 5, in <module>
    main()
  File "/home/Git-Auto-Deploy/gitautodeploy/gitautodeploy.py", line 449, in main
    app.setup(config)
  File "/home/Git-Auto-Deploy/gitautodeploy/gitautodeploy.py", line 250, in setup
    logger.addHandler(logging.NullHandler())
AttributeError: 'module' object has no attribute 'NullHandler'`

**Comment by Letme** [comment]
Not looking into source but what does your config.json have as logging level (`"log-level": "INFO"`)

**Comment by drsaluml** [comment]
V0.2.5 up ,  Not be resolved

https://github.com/olipo186/Git-Auto-Deploy/issues/118

**Comment by drsaluml** [comment]
```
        try:
            from logging import NullHandler
        except ImportError:
            from logging import Handler

            class NullHandler(Handler):
                def emit(self, record):
                    pass
```

```
        # Enable console output?
        if ('quiet' in self._config and self._config['quiet']) or ('daemon-mode' in self._config and self._config['daemon-mode']):
            logger.addHandler(NullHandler())
        else:
```

**Comment by Letme** [comment]
What do you have in config.json as logging level?

**Comment by olipo186** [comment]
What version of python are you using? 2.6? GAD will need 2.7 to run smoothly. Please reopen if problem persists.
