### ISSUE TITLE
Add Bitbucket compatibility

### ISSUE THREAD

**Issue by mxcoder** [olipo186/Git-Auto-Deploy#17]
Hi, just found your nice fork of this code, after creating my own :) duh!

I have some of my projects on Bitbucket, so .. I got this:
https://github.com/mxcoder/GitAutoDeploy

I think it would be great if we can collaborate on adding bitbucket's hooks to your version.
Please let me know if you are interested on it, and if I can help you anyhow, I'm not a python dev, but well, just let  me know.

In case you're interested, the "bad" parts of bitbucket is that it uses application/json for the pullrequest hook, and form-urlencoded for the push hook. So, had to deal with that.

Regards!

**Comment by olipo186** [comment]
Hi guys,

I did some refactoring of the code base and added a few lines for Bitbucket while I was at it. I believe it should work now. I have tested it on my setup, but any additional testing efforts is greatly appreciated. :)
