### ISSUE TITLE
gitlab problem

### ISSUE THREAD

**Issue by geobde** [olipo186/Git-Auto-Deploy#170]
i try to make this work with gitlab and don't work for my and throws my errors
have anyone any idea the correct configuration for gitlab???

**Comment by Letme** [comment]
Yeah its really simple - same as for github. What are your problems?

Major points are:
 - you need to add deploy key of a server to your project
 - you need to add a webhook to server running git-auto-deploy (with "secret-token") that triggers on event when you would like to deploy (like push to master)

**Comment by geobde** [comment]
i follow the steps and when i push a file to gitlab show my this error

2017-02-16 13:44:15,681 [INFO ]  Incoming request from 10.0.2.15:38284
2017-02-16 13:44:15,889 [INFO ]  Handling the request with GitLabRequestParser
2017-02-16 13:44:15,919 [INFO ]  Received 'System Hook' event from GitLab
2017-02-16 13:44:15,920 [WARNI]  The URLs references in the webhook did not match any repository entry in the config. For this webhook to work, make sure you have at least one repository configured with one of the following URLs; git@linux:root/auto-deploy.git, http://linux/root/auto-deploy.git, git@linux:root/auto-deploy.git
2017-02-16 13:44:15,920 [INFO ]  10.0.2.15 - code 400, message Bad request
2017-02-16 13:44:15,920 [INFO ]  10.0.2.15 - "POST / HTTP/1.1" 400 -
2017-02-16 13:44:15,920 [ERROR]  No matching repository config

**Comment by Letme** [comment]
The error is descriptive enough. Do you have a rule matching git@linux:root/auto-deploy.git (seems like that is a repo generating a webhook) in config file?

**Comment by geobde** [comment]
this is my configuration file. Do you have any ideas?
..................................................................................................
  "repositories": [
    {

    {
      "url": "git@linux:root/auto-deploy.git",
      "path": "~/repositories/gitignore",
      "deploy": "echo deploying after pull request"
   },
      "filters": [
        {
          "type": "pull-request-filter",
          "action": "closed",
          "ref": "testing-branch"
        }
      ]
    }
  ]
}

**Comment by Letme** [comment]
Umn formatting is a bit lost. I would remove filters since gitlab does not have a pull request so that might also be it. You mark on webhook in Gitlab that push will trigger the webhook (kinda speaking by memory here I think it is Service or Integration nowdays). Then if you want it on testing-branch then simply put 
`"branch":"testing-branch"` on same level as you have `"url"` and  `"path"`

**Comment by geobde** [comment]
i remove the filters but the same error this is my gitlab configuration fir web hooks maybe is here the error

![screenshot from 2017-02-16 15-11-10](https://cloud.githubusercontent.com/assets/14848156/23022631/9391c83a-f45a-11e6-9708-a639b4eb64c9.png)

**Comment by Letme** [comment]
You want project webhook not a system one - for sure. That is in project "wheel menu" under integrations (checked)
Next thing you have SSL verification enables yet your address is http - pick one (SSL can be pain).

**Comment by geobde** [comment]
i make the changes and return me this message when i test it
thanks for help a lot
![screenshot from 2017-02-16 17-43-10](https://cloud.githubusercontent.com/assets/14848156/23028261/85ee76b4-f46f-11e6-8cef-dcd3372f4b61.png)

**Comment by Letme** [comment]
Ok, that is the correct webhook site, but I cannot see your created hook (that push events tick is ok). I hope you set a secret token as well (`"secret-token":` as part of `"repositories"` array and it matches the one on Gitlab Integrations).

Anyway 400 error on the gitlab means you get through, but it might be SSL verification? Wrong port might be next thing . Check the git-auto-deploy log (declared in `"logfilepath"`) for more info.

**Comment by Letme** [comment]
Had some time - this is how my repositories slot seems like
``` 
{
      "url": "git@example.com:group/projectname.git",
      "branch": "master",
      "remote": "origin",
      "path": "/path/to/where/repo/is/served",
      "deploy": "echo wherever",
      "secret-token": "secrettokenthatshouldbepersonalizedorgeneratedrandomly"
},
```

**Comment by geobde** [comment]
in the secret token i put whatever i want?
can you explain what i need to enter a path?

my screenshot from the webhook

![screenshot from 2017-02-16 18-10-22](https://cloud.githubusercontent.com/assets/14848156/23029570/acfec1ba-f473-11e6-94c4-8f8520f04391.png)

**Comment by Letme** [comment]
Yes, secret token you put whatever you want but it needs to match the one you added to webhook (I do not know if you did.  Screenshot/webhook seems fine (without SSL).

Path is your server's local path where deploy will clone the repository.

**Comment by geobde** [comment]
I make the changes and when i test the webhook shows my this error

![screenshot from 2017-02-17 12-50-58](https://cloud.githubusercontent.com/assets/14848156/23063000/08aeb77a-f511-11e6-8b4e-3dbeaa126067.png)

**Comment by Letme** [comment]
I assume you set git-auto-deploy to listen on 0.0.0.0:8001? If so, hook setup should not be on 0.0.0.0. -  it should probably be 127.0.0.1 if you are doing this on same machine or even better just put domainname (linux:8001) of the machine instead so that it "might" go outside to pick route, but you let it figure out itself.

**Comment by geobde** [comment]
where to set the port to listen  in git-auto-deploy.conf.json?

**Comment by Letme** [comment]
Why don't you check the sample config?  Git-Auto-Deploy/config.json.sample

**Comment by olipo186** [comment]
Did it work out after all the help and support from @Letme ? Please reopen otherwise.

**Comment by geobde** [comment]
Finally it doesn't work but i used another script in php.
