### ISSUE TITLE
git lab push hook events veeeeery slow

### ISSUE THREAD

**Issue by Jossnaz** [olipo186/Git-Auto-Deploy#178]
i completed today several push events, nothing happened minutes afterwards. The push events tested successfully, and they work, it just takes gitlab some 3-10 minutes to actually call the webhook. I have this problem as of today, worked fine yesterday etc. 

Now this is very boring and tedious. is there a command line way to do what gitlab is doing via push event, e.g. start the deployment process via cli? or i have to write my own shell script?

**Comment by Letme** [comment]
There is test trigger button in gitlab when you created a build trigger hook

**Comment by olipo186** [comment]
I agree, the test button sounds like a good approach. This also doesn't sound line an issue with GAD, more like some kind of problem with a GitLab installation
