### ISSUE TITLE
GAD must be started as a python module on Ubuntu

### ISSUE THREAD

**Issue by lukinko** [olipo186/Git-Auto-Deploy#179]
After commit number c013cb6 I have such errors on Ubuntu when trying to run the GAD from a init script:

● git-auto-deploy.service - LSB: Script to start Autodeploy Git
   Loaded: loaded (/etc/init.d/git-auto-deploy; bad; vendor preset: enabled)
   Active: active (exited) since Thu 2017-04-13 16:35:14 CEST; 4h 36min ago
     Docs: man:systemd-sysv-generator(8)

Apr 13 16:35:14 dev-node1 systemd[1]: Starting LSB: Script to start Autodeploy Git...
Apr 13 16:35:14 dev-node1 git-auto-deploy[12255]: Starting..
Apr 13 16:35:14 dev-node1 git-auto-deploy[12255]: Critical - GAD must be started as a python module, for example using python -m gitautodeploy

**Comment by Letme** [comment]
Can you paste the init script?

**Comment by Letme** [comment]
https://github.com/olipo186/Git-Auto-Deploy/blob/master/platforms/debian/stdeb/git-auto-deploy.init#L122 <-- this might need -m on that line (no idea how service is deployed...)

**Comment by olipo186** [comment]
Sorry for the troubles, it's fixed again in v0.15.

```
apt-get update
apt-get upgrade git-auto-deploy
```
