### ISSUE TITLE
Unable to run

### ISSUE THREAD

**Issue by rajneeshojha** [olipo186/Git-Auto-Deploy#188]
when running this :
`/usr/bin/python -m   /home/admin/web/deploy.example.com/public_html/Git-Auto-Deploy/gitautodeploy --config /home/admin/web/deploy.example.com/public_html/Git-Auto-Deploy/config.json`

getting error:
`/usr/bin/python: Import by filename is not supported.`

**Comment by scriptburn** [comment]
anyway i found what i was looking for , 
https://github.com/scriptburn/git-auto-deploy

**Comment by olipo186** [comment]
@rajneeshojha, what python version are you running?

**Comment by olipo186** [comment]
Please reopen with details about python version if the problem persists.

**Comment by lboaretto** [comment]
Same here

Distributor ID:	Debian
Description:	Debian GNU/Linux 9.1 (stretch)
Release:	9.1
Codename:	stretch

Python 2.7.13
