### ISSUE TITLE
Centos 7 shell script start/stop

### ISSUE THREAD

**Issue by drsaluml** [olipo186/Git-Auto-Deploy#192]
Centos 7 shell script start/stop

Start
`GitAutoDeploy_Service.sh start`

Stop
`GitAutoDeploy_Service.sh stop`

Stop
`GitAutoDeploy_Service.sh restart`

[GitAutoDeploy_Service.zip](https://github.com/olipo186/Git-Auto-Deploy/files/1225760/GitAutoDeploy_Service.zip)

**Comment by olipo186** [comment]
Thanks! 👍 I put it here:

https://github.com/olipo186/Git-Auto-Deploy/blob/master/docs/Start%20automatically%20on%20boot.md#centos-7

**Comment by mynukeviet** [comment]
You can edit for centos 6?
