### ISSUE TITLE
SSL issue with Let’s Encrypt

### ISSUE THREAD

**Issue by whimzee** [olipo186/Git-Auto-Deploy#205]
When you use Let's Encrypt, your certificates are stored under ` /etc/letsencrypt/live/example.com/`

My configuration is as follows:
```
"ssl-key": "/etc/letsencrypt/live/example.com/privkey.pem", 
"ssl-cert": "/etc/letsencrypt/live/example.com/fullchain.pem",
```

When running with sudo, the SSL certificate is verified and the script works as normal, but since this isn't preferred I want to run it as another user. 

When trying to use the script as as user I get this error:
```
[CRITI]  Unable to activate SSL: File does not exist: /etc/letsencrypt/live/example.com/fullchain.pem
```
The file clearly exists, as proven by running it with sudo.

**Comment by Letme** [comment]
So directory permissions there are maked as write for at least a group? (I would expect that user to be at least in some root group). LetsEncrypt has its own scheduler, so no idea why arent you using their inbuilt cron to refresh certificates.

Anyway this more seems like either the command you are using does not create new file (specially above you have example.com, below in report you have just example) properly, you do not have write permission to /etc/letsencrypt/live (this would be my guess). I do not see how this is issue of git-auto-deploy.

**Comment by whimzee** [comment]
Sorry, I replaced my domain to example.com for privacy reasons and forgot to add .com. My configuration is valid, I just scrubbed the original domain. I fixed it in my example now.

> LetsEncrypt has its own scheduler, so no idea why arent you using their inbuilt cron to refresh certificates.

Can you elaborate a bit on this? I use Certbot to manage the certificate renewals. The path I provided is simply where they are stored so applications like git-auto-deploy can use them.

> you do not have write permission to /etc/letsencrypt/live (this would be my guess).

Why would I need write permission? Certbot is the only program supposed to write to the files. Am I not simply providing the path to the SSL certificate so it can be used by the webserver in git-auto-deploy?

How would I provide the SSL path properly so it works with Let's Encrypt? There isn't a lot of documentation when it comes to SSL in this repo...

**Comment by Letme** [comment]
Last time I checked /etc/letsencrypt/live is group (usually root) readable, so make sure you add your git-auto-deploy to that group. I doubt you can change the directory to make it other readable. So if you are just passing the certificate for git-auto-deploy then it should be readable by user running git-auto-deploy.

Is that the case?

**Comment by whimzee** [comment]
It's not the case. I get permission denied errors, even by trying to read the contents manually with `cat`, which I just found out about. Maybe this is something I need to get right first with Let's Encrypt? Struggling to find any kind of documentation on permissions in the `/etc/letsencrypt/live` directory.

I'm using the pure python version of the script - since it wouldn't me download it from apt-get - so I can't add the permission to it. If I recall correctly python runs on the user, inheriting their permissions?

**Comment by Letme** [comment]
I am a bit away from my server atm so I cannot double check. For sure the python script runs with the permissions of the user lunching it. git-auto-deploy is no different, so you will need to check things with that user.

If you confirmed that file exists and you have read rights (you wrote that it is not the case, yet you say `cat` does not work) to it with the user running git-auto-deploy, maybe `.pem` needs also `+x`? It is a simple check to try.

Again this has nothing to do with Lets Encrypt, as also other certificates should be kept as private as possible. If all paths are correct, then permissions might not be. You can double check with simple copy of file path and then do ls or cat from the user running git-auto-deploy (`sudo -u user -H ls /etc/letsencrypt/live/example/fullchain.pem`)

**Comment by whimzee** [comment]
```
$ sudo -u wz -H ls /etc/letsencrypt/live/example.com/fullchain.pem
ls: cannot access '/etc/letsencrypt/live/example.com/fullchain.pem': Permission denied
```

```
$ ls -l /etc/letsencrypt/live/example.com/fullchain.pem
lrwxrwxrwx 1 wz root 37 Feb 14 18:28 /etc/letsencrypt/live/example.com/fullchain.pem -> ../../archive/example.com/fullchain1.pem
```

Should have full access...

**Comment by Letme** [comment]
That is link permission not file permission.

To get file permission you need:
```
sudo ls -l /etc/letsencrypt/live/example.com/fullchain.pem../../archive/example.com/fullchain1.pem 
 -rw-r--r-- 1 root root 3501 Jan 17 01:26 /etc/letsencrypt/live/....
```
As you can see for me this is root readable/writeable (like you would need for renewals and others have read only - which should suffice). 

What is interesting for me is that there is no group readable rights on parent directory (that's why we cant get in). So I would add a read to group (hopefully you put your user in that group as read for others to me seems a bit too much)

```
sudo ls /etc/letsencrypt/live/ -al
drwx------ 12 root root 4096 Nov 11 12:40 .
drwxr-xr-x  8 root root 4096 Feb 19 01:46 ..
drwxr-xr-x  2 root root 4096 Jan 11 01:24 example.com
```

**Comment by whimzee** [comment]
I ended up going to the folder that the links were going to and added my permissions to them. I didn't realize that everything in `live` was a symlink. Everything works flawlessly now. Hopefully this thread may be of help to others who are struggling with Let's Encrypt integration.
