### ISSUE TITLE
problem with page

### ISSUE THREAD

**Issue by Kaczuc** [olipo186/Git-Auto-Deploy#230]
![image](https://user-images.githubusercontent.com/43011737/57585850-dcae6a80-74ed-11e9-8011-d3de4e41b0e4.png)

**Comment by Letme** [comment]
And what is the problem? It clearly tells you that your configuration did not enable Web UI - or you did?

**Comment by Kaczuc** [comment]
How to do it?

**Comment by Letme** [comment]
https://github.com/olipo186/Git-Auto-Deploy/blob/master/config.json.sample#L17-L21

**Comment by Kaczuc** [comment]
Thanks You

**Comment by Letme** [comment]
No problem - that is the only place I know where this is mentioned. Close the issue when you are happy.

**Comment by Kaczuc** [comment]
```
  HTTP server options
  "http-enabled": true,
  "http-host": "0.0.0.0",
  "http-port": 8001,

  // HTTPS server options
  //"https-enabled": true,
  //"https-host": "0.0.0.0",
  //"https-port": 8002,

  // Web socket server options (used by web UI for real time updates)
  //"wss-enabled": false,
  //"wss-host": "0.0.0.0",
  //"wss-port": 8003,

    Web user interface options
  "web-ui-enabled": true,
  "web-ui-username": null,
  "web-ui-password": null,
  "web-ui-whitelist": ["127.0.0.1"],
```
Despite the fact that these variables are not present, it does not work now, even the page does not load

**Comment by Letme** [comment]
Are you trying to access this from server itself? Otherwise you need to fill in your external ip or domain name...

**Comment by Kaczuc** [comment]
So, I connect to the address of my vps on port 8001, you will show your configurations how does it look like?

**Comment by Letme** [comment]
What do you mean? In whitelist add something.example.com instead of 127.0.... (Localhost) and it will listen to that dns/ip. With current localhost it listens only for server local connections, so unless you use browser on server, it will not respond.

**Comment by Kaczuc** [comment]
```
	HTTP server options
	"http-enabled": true,
	"http-host": "0.0.0.0",
	"http-port": 8001,

	// HTTPS server options
	//"https-enabled": true,
	//"https-host": "0.0.0.0",
	//"https-port": 8002,

	//Web socket server options (used by web UI for real time updates)
	//"wss-enabled": true,
	//"wss-host": "0.0.0.0",
	//"wss-port": 8003,

	Web user interface options
	"web-ui-enabled": true,
	"web-ui-username": null,
	"web-ui-password": null,
	"web-ui-whitelist": ["my_adres_ip_vps"],
```

Despite the use of this configuration, the site does not even search on port 8001

**Comment by Letme** [comment]
But 8001 port is where program listenes for deploy triggers not where webui is. So while I would leave ip there as 0.0.0.0 I would expect webui to be running on port 80 as a normal webapp.

**Comment by Letme** [comment]
Maube I missunderstood but I understood you are trying to set up webUI and everything else works as expected...

**Comment by Kaczuc** [comment]
Currently, even the site does not work, the site works if the webui is off

**Comment by Kaczuc** [comment]
I have everything turned on now and it still does not work, the site is loading, but I am wrong with the lack of UI showing me your configurations

**Comment by Letme** [comment]
My configuration is exactly expanded example. I do have username and password set for webui. I also whitelisted only my own home IP there (so maybe if you put 0.0.0.0 it should work, if you do not have a static home ip). So maybe that is the confusion as I told you to whitelist your server domain/ip, but you should in fact other. I also piped it through nginx some time ago and the localhost ip was working as nginx was requesting...

**Comment by Kaczuc** [comment]
So why is it not working for me if I unlock the webui?

**Comment by Kaczuc** [comment]
I managed to run the web page but now I have information that my ip address is not allowed access.

**Comment by Letme** [comment]
That is an improvement. I would check the whitelist setting and what you have there...

**Comment by Kaczuc** [comment]
I added my ip address to the list but now
![image](https://user-images.githubusercontent.com/43011737/57801678-8727c700-7754-11e9-8132-1ab55990a57a.png)

**Comment by Letme** [comment]
This tells you you need to set username and password in the config file...

**Comment by Kaczuc** [comment]
Ok, but when I set my login and password instead of null, I do not want to load the page

**Comment by Kaczuc** [comment]
Can you also tell me how to add another ip address to the white list just need to copy the columns responsible for the web ui user?

**Comment by Letme** [comment]
Its json array which means comma separated values. Did you add quotes around the username and password?

**Comment by Kaczuc** [comment]
Thank you for everything works
