### ISSUE TITLE
deploy change permission wrong 

### ISSUE THREAD

**Issue by matamune94** [olipo186/Git-Auto-Deploy#243]
i set deploy in config : "yarn install && yarn build"

when build done i see files change permission is 640 , so nginx can't access files . how can fix, please .

**Comment by Letme** [comment]
Add nginx to git auto deploy group or git autodeploy group set as www-data (default nginx). Alternatively you can chown as well...

**Comment by matamune94** [comment]
Can you give me an example?

**Comment by Letme** [comment]
`chown git-auto-deploy:www-data filename`

or google how to add www-data user to git-auto-deploy group (or whatever user/group that files are in).

**Comment by matamune94** [comment]
so in deploy i can set : chown -R www-data:nginx /var/www/website/dist ?

**Comment by matamune94** [comment]
@Letme hi sir
i want change permission when build done by find /var/www/test/ -type d -exec chmod 755 {} \;
my test
"deploy": "yarn install && yarn build && find /var/www/test/ -type d -exec chmod 755 {} \/;"
and not working but i try in command it working

**Comment by Letme** [comment]
Again not working. Can you be a bit more explicit what is in logs?

**Comment by matamune94** [comment]
Now it working thank for support

**Comment by Letme** [comment]
What did you do, so others ending on this issue will know as well.

**Comment by matamune94** [comment]
I did as you instructed
