### ISSUE TITLE
Ask GitHub staff to unlink the project

### ISSUE THREAD

**Issue by alexandernst** [olipo186/Git-Auto-Deploy#35]
This project appears as a fork of `logsol/GitHub-Auto-Deploy`, but the projects have diverted so much that they are not even similar anymore. Ask a GitHub admin (from contact area) to unlink this project from the other one.

**Comment by alexandernst** [comment]
I will proceed,  unless you @olipo186 don't want me to.

**Comment by olipo186** [comment]
Please do :) I Agree

**Comment by alexandernst** [comment]
@olipo186 GitHub staff needs your permission :)

> Hi Alexander,
> 
> Please ask the owner of the olipo186 account contact us with this request while signed into their account:
> 
> https://github.com/contact
> 
> Thanks,
> James
> 
> > Hi!
> >
> > I'm a collaborator of a project that was forked long time ago. The original project and ours diverted > so much that they are not even similar nowadays, so we'd like to "unlink" them, aka, hide that "this project is a fork on XYZ project" message that appears next to the projects name.
> >
> > Link to the project (and to the issue where we talked about this): https://github.com/olipo186/Git-Auto-Deploy/issues/35
> >
> > Regards!

**Comment by olipo186** [comment]
They got back to me moments ago, should be solved now. :)

**Comment by alexandernst** [comment]
Cool! \o/ :+1:
