### ISSUE TITLE
Is it possible to run scripts after deploy?

### ISSUE THREAD

**Issue by Akhanto** [olipo186/Git-Auto-Deploy#38]
I'd like to run a script that corrects permissions after deploying. Is it possible to call that through this tool?

**Comment by alexandernst** [comment]
Please read the docs. It's the second parameter of `global_deploy`. https://github.com/olipo186/Git-Auto-Deploy/blob/6a565706a8b25e18ec4deb098aa96743318384c6/GitAutoDeploy.conf.json.example#L5

**Comment by Akhanto** [comment]
Sorry if I don't see something obvious but I can't see anything about scripts in your docs. I already tried to attach the path to a shellscript after the two echoes but nothing happened. 
The script looks like that: 

{
        "pidfilepath": "~/.gitautodeploy.pid",
        "host": "0.0.0.0",
        "port": 8001,
        "global_deploy": [
                "echo Deploy started!",
                "echo Deploy completed!",
                "/path/to/script.sh"
        ]

**Comment by alexandernst** [comment]
No. You must write your command in the place of the second item in the `global_deploy` list. It should look like:

    "global_deploy": [
        "echo Deploy started!",
        "/path/to/script.sh"
    ]
