### ISSUE TITLE
Permission denied

### ISSUE THREAD

**Issue by nguyenkims** [olipo186/Git-Auto-Deploy#41]
Hi

I try to install all the dependencies in the hook by adding `bower install` into the deploy.sh whose absolute path (`/home/son/preprod/deploy.sh`) is put into the "deploy" path in the config file. However, I got this error message when the hook run

    /bin/sh: 1: /home/son/preprod/deploy.sh: Permission denied

Does anyone have an idea why ?
I have tried doing a `cd` before running the script but still got the same error message.

Thanks,
Son.

**Comment by olipo186** [comment]
Have you set the x-flag?

```chmod +x /home/son/preprod/deploy.sh```

**Comment by nguyenkims** [comment]
You're right, the -x flag is the culprit ! So I just copied the script content to the config file and the problem is fixed.

This is unrelated but actually I don't quite understand why when I chmod +x for the script on my system (mac), git doesn't recognize this as a change whereas on the server (ubuntu), git can see this.

**Comment by olipo186** [comment]
If I understand you correctly, you're unable to commit permission changes from your mac. Maybe the default git configuration differs between ubuntu and your mac. If that is the case, changing the git config on your mac might help;

```git config core.filemode true```

Good luck!

Regards,
Oliver

**Comment by nguyenkims** [comment]
Thanks,  your command works ! Git can now see the file permissions changes.
Thanks very much !

Son.
