### ISSUE TITLE
Question: Multiple repo support?

### ISSUE THREAD

**Issue by calebpaine** [olipo186/Git-Auto-Deploy#43]
I have many different sites with corresponding repositories, the config *looks* like it might support this usage, but the docs don't mention it.

**Comment by olipo186** [comment]
Yes, it does support multiple repositories. The docs needs an update.

**Comment by calebpaine** [comment]
Also, some basic setup instructions as well. Does this require a normal repo on the server, (and thus the .git directory is now publicly accessible), or do I follow some of the common guides and setup a bare repo and Git-Auto-Deploy handles the GIT_WORK_TREE fun?

**Comment by olipo186** [comment]
Hi! Docs have now been updated in PR https://github.com/olipo186/Git-Auto-Deploy/pull/75
