### ISSUE TITLE
Use a log file

### ISSUE THREAD

**Issue by cyberjacob** [olipo186/Git-Auto-Deploy#46]
It would be useful if this produced a log file with everything it does (git pull results, deploy command statuses, etc)

**Comment by linkdesu** [comment]
I agree definitly ! 

After start with service command  , Git-Auto-Deploy is not work , but it still return 200 OK to bitbucket .

It's really strange ...

**Comment by olipo186** [comment]
I agree, a log file would be a nice feature :)

@linkdesu If you think that is a bug, can you please raise a separate issue with more detailed information?
