### ISSUE TITLE
Make it configurable by environment variables (for Docker)

### ISSUE THREAD

**Issue by iBobik** [olipo186/Git-Auto-Deploy#47]
As I described in [the future README](https://github.com/iBobik/Git-Auto-Deploy/blob/patch-1/README.md#or-run-it-configured-by-environment-variables), script should fetch basic configuration from Docker ENV variables, even if no config file is specified.

Could you help me to add this feature to the script? I guess we need to add to `get_config()` something like this:

- not raise exceptions on lines 403 and 410 if there is env variable AUTODEPLOY_URL
- add entry to beginning of `self._config['repositories']` list from all env variables before cycle on 418 begins

Am I on the right way?

**Comment by olipo186** [comment]
Yes, I like the idea :) Fixed in 82316c9008259a8129327016f2013d4518a14679 and b5262a2a01da1f1410fcdaf3fb1f5d547425b453. Also updated the README. Please have a look when you get the chance.
