### ISSUE TITLE
Error when set url as git with --sshkey-gen

### ISSUE THREAD

**Issue by loma** [olipo186/Git-Auto-Deploy#50]
I've set the url in the config as git url and using --sshkey-gen argument to start the daemon, and it shows me this error. It is working fine with HTTPS url.

Traceback (most recent call last):
  File "GitAutoDeploy.py", line 661, in <module>
    app.run()
  File "GitAutoDeploy.py", line 585, in run
    self.ssh_key_scan()
  File "GitAutoDeploy.py", line 480, in ssh_key_scan
    port = repository['port']
KeyError: 'port'

**Comment by alexandernst** [comment]
You're missing the `port` key/value in your config.

**Comment by loma** [comment]
yes, you were right, it works when i add the key/value for port
"port": "9418"

btw, should this port be default to 9418 unless set?

**Comment by alexandernst** [comment]
The default port is `8001` (same as GitLab's). For the port key to be <b>unset</b> you must delete it from your config file, in which case it's just an error.
