### ISSUE TITLE
Port is inaccessible

### ISSUE THREAD

**Issue by fronteed** [olipo186/Git-Auto-Deploy#51]
This product looks good, but it likely doesn't work well with Gitlab.

I didn't use docker for installation, everything is configured from the Makefile, gitautodeploy is launched using `/etc/init.d/gitautodeploy start`

I get this message on `start`:

```
Directory /home/deploy/www/test not found
Cloning into '/home/deploy/www/test'...
remote: Counting objects: 12, done.
remote: Compressing objects: 100% (12/12), done.
remote: Total 12 (delta 2), reused 0 (delta 0)
Receiving objects: 100% (12/12), 261.06 KiB | 0 bytes/s, done.
Resolving deltas: 100% (2/2), done.
Checking connectivity... done.
Repository git@gitlab.com:fronteed/deploy.git successfully cloned
Starting Git Auto Deploy in daemon mode
```

As a result, repo is successfully cloned into `/home/deploy/www/test/`!

Here's the code from `/opt/Git-Auto-Deploy/GitAutoDeploy.conf.json`:
```
{
        "pidfilepath": "/var/run/gitautodeploy/gitautodeploy.pid",
        "host": "localhost",
        "port": 8001,
        "global_deploy": [
                "echo Deploy started!",
                "echo Deploy completed!"
        ],
        "repositories":
        [{
                "url": "git@gitlab.com:fronteed/test.git",
                "branch": "master",
                "path": "/home/deploy/www/test"
        }]
}
```

I've a droplet at DO (digitalocean.com), so my host is the static IP, which looks like http://m.y.i.p:8001 (your-host:8001). I'm trying to paste this address into the URL field in "web hooks" section of my project at Gitlab.com. I get an error "Hook execution failed. Ensure hook URL is correct and service is up". When I push updates into repo, I don't see any changes at `/home/deploy/www/test` :disappointed: 

Summary:
- public keys are likely ok, since repo is nicely cloned at the beginning.
- web hook at 8001 port doesn't work for Gitlab, while it's reachable and open.

I'm using Ubuntu 14.04, Nginx and Git v2.6.3. 

`ps -ef | grep python`:
```
root    30370    1  0 16:22 ?     00:00:00 python /opt/Git-Auto-Deploy/GitAutoDeploy.py --daemon-mode
```

`lsof -i :8001`
```
COMMAND   PID USER   FD   TYPE   DEVICE SIZE/OFF NODE NAME
python  30370 root    3u  IPv4 17339996      0t0  TCP *:8001 (LISTEN)
```

**Am I doing something wrong?**

**Comment by codybuell** [comment]
I'm currently using with GitLab successfully.  Issue appears to be with your droplet configuration.  Ensure that you have port 8001 open to GitLab instance on the droplet firewall.  On GitLab server `nc -vz 46.101.185.33 8001` to check.

**Comment by fronteed** [comment]
@codybuell thanks for reply.

I get this message `Connection to 46.101.185.33 8001 port [tcp/*] succeeded!`
I'm using Ubuntu 14.04, Nginx and Git v2.6.3. 

Commands `gitautodeploy stop/start/restart` likely work, since process is plugging 8001 port (`lsof -i :8001`).
I've switched off all the firewalls related stuff, tried to reload gitautodeploy - hook test still fails.
What Git version do you have, @codybuell?

**Comment by fronteed** [comment]
@codybuell thanks for reply!

I get this message from osx terminal `nc: connectx to 46.101.185.33 port 8001 (tcp) failed: Operation timed out`.

```
$ ufw status numbered
Status: active

     To                         Action      From
     --                         ------      ----
[ 1] 22                         ALLOW IN    Anywhere
[ 2] 8001                       ALLOW IN    Anywhere
[ 3] 80                         ALLOW IN    Anywhere
[ 4] 8001/tcp                   ALLOW IN    Anywhere
[ 5] 443                        ALLOW IN    Anywhere
[ 6] 80 on eth0                 ALLOW IN    Anywhere
[ 7] 3306 on eth1               ALLOW IN    Anywhere
[ 8] 22 (v6)                    ALLOW IN    Anywhere (v6)
[ 9] 8001 (v6)                  ALLOW IN    Anywhere (v6)
[10] 80 (v6)                    ALLOW IN    Anywhere (v6)
[11] 8001/tcp (v6)              ALLOW IN    Anywhere (v6)
[12] 443 (v6)                   ALLOW IN    Anywhere (v6)
[13] 80 (v6) on eth0            ALLOW IN    Anywhere (v6)
[14] 3306 (v6) on eth1          ALLOW IN    Anywhere (v6)
```

Commands `gitautodeploy stop/start/restart` likely work, since process is plugging into 8001 port (`lsof -i :8001`), while hook test still fails.

Any thoughts? :disappointed:

**Comment by codybuell** [comment]
Hmm... Given your firewall output you should have been able to successfully connect from your OS X terminal with net cat.  Sounds like something else along the path is blocking your connection.  I'm not familiar enough with digital ocean to point you in the right direction but it doesn't appear to be a problem with gitautodeploy.  What does your netstat output look like?  `netstat -ant | grep LIST`

**Comment by codybuell** [comment]
Also, any difference if you change your host from localhost to 0.0.0.0 in your gitautodeploy config?

**Comment by fronteed** [comment]
@codybuell I love you man, big thanks! :+1: 

I've just restarted the server, changed `localhost` to `0.0.0.0` and now it finally works! YEAH!
