### ISSUE TITLE
Username and password

### ISSUE THREAD

**Issue by bhtw** [olipo186/Git-Auto-Deploy#53]
Hi

I got it up and running towards my GitLab repos, but every time I do a push that triggers the git pull from Git-Auto-Deploy, it asks for username and password. I cannot find anything in the documentation that explains how to get around this. Maybe I'm missing out on something here, but please explain how to do this. Shall I add something in the conf.json file?
Thanks.

**Comment by alexandernst** [comment]
If it's asking you for the user/password it means that it's trying to fetch the repo without your public key (or that your repo is forcing auth by user/passwd). Either way, it's not a fault in this script.

**Comment by bhtw** [comment]
Hi, I know it's not an issue in this script. So sorry for putting it here, but I wanted to ask a question and didn't know where else to put it.
My public .ssh key is in place and other git repos work fine with both pull and push requests, therefore I wonder if username and password needs to be placed in the config file or ssh public key path, the key itself or something related to user/pwd anywhere?
If not, any pointers to how I can fix this would be appreciated.
Thanks.

**Comment by bhtw** [comment]
I figured it out. I was using the http link from GitLab and not ssh link in the config file. Therefore it asked for username and password everytime it pulled. Now it works fine.
Sorry for the inconvenience.
