### ISSUE TITLE
git clone/pull permissions

### ISSUE THREAD

**Issue by DirectorX** [olipo186/Git-Auto-Deploy#58]
allow configuration of setting uid/gid per repo

**Comment by fThues** [comment]
+1

**Comment by DirectorX** [comment]
#59 during this pr , @alexandernst told me that the script should not run as root user.. so now.. i cant tell how git clone/pull permissions management will work

**Comment by alexandernst** [comment]
Indeed. only a bunch of processes in a linux machine should run as root. Because of that, I'm not sure this could be ever implemented. Anyways, I'd like to know what would be a real-world scenario for this feature request. Why would you need to set the uid/gid of the `git clone` process?

**Comment by DirectorX** [comment]
i wanted this feature because i was sure the script run as root user...

**Comment by alexandernst** [comment]
Adding features just because it's possible is (usually) not a good idea. Are there any real benefits of being able to set the uid/gid?

**Comment by DirectorX** [comment]
the one and only benefit is the files that created using the clone operation will belong to spesific (weak) user

**Comment by alexandernst** [comment]
You can already transfer the ownership of cloned files with the post-clone command option (running `chmod` and/or `chown`)

**Comment by DirectorX** [comment]
you are right but not as `www-data` .. :confused: 
well this issue should be closed

**Comment by alexandernst** [comment]
There is no reason why `www-data` couldn't run `chown`. You don't need `root` permissions to do so.
