### ISSUE TITLE
Deploy commands not being executed

### ISSUE THREAD

**Issue by adrianoprospero** [olipo186/Git-Auto-Deploy#61]
Hi,
I'm trying to execute a deployment command after the **git pull**, but I'm not getting to do it. I put a command in the "deploy" option, in repository configuration, but nothing occurs, just the pull. I am doing anything wrong or could it be a bug?

Thanks!

**Comment by alexandernst** [comment]
Well, first of all, are you sure it's not being executed? What is the command you're trying to execute? Keep in mind that the command is executed with the same user the service itself is being executed.

**Comment by adrianoprospero** [comment]
My config file:

```
{
        "pidfilepath": "~/.gitautodeploy.pid",
        "host": "123.456.789.10",
        "port": 8085,
        "global_deploy": [
                "echo Deploy started!",
                "echo Deploy completed!"
        ],
        "repositories":
        [{
                "url": "git@myhost.com:devmacae/intranetufrj-aux.git",
                "branch": "master",
                "remote": "origin",
                "path": "~/intranet-aux",
                "deploy": "echo test > /tmp/deploying.txt"
        }]
}
```

**Comment by adrianoprospero** [comment]
I tested a simple command to just write a message in a file, but isn't working...

**Comment by adrianoprospero** [comment]
Should the deploy command be a .sh file?

**Comment by Nikey** [comment]
u are sure that you hooked it properly in your gitlab?

**Comment by adrianoprospero** [comment]
Yes, because the files are updated correctly, but the command isn't being
executed...

On Mon, Feb 22, 2016 at 8:55 PM, Nikey <notifications@github.com> wrote:

> u are sure that you hooked it properly in your gitlab?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/olipo186/Git-Auto-Deploy/issues/61#issuecomment-187443081>
> .
>



-- 
Adriano de Oliveira Gonçalves
Programador / Analista
Campos-RJ / Phone: (21) 98737-6629 (TIM)
contato@adrianoweb.com.br

**Comment by olipo186** [comment]
Hi,

Are you running Git-Auto-Deplouy as a service or in daemon mode? If so, please try and run it from the shell, i.e. ```python GitAutoDeploy.py``` and then trigger the git events. Do you get any errors?

BR,
Oliver

**Comment by olipo186** [comment]
I'm closing this issue for now. @adrianoprospero please get back if the issue persists.
