### ISSUE TITLE
Problems with GitLab's SSH URL.

### ISSUE THREAD

**Issue by jstnmthw** [olipo186/Git-Auto-Deploy#62]
When adding an SSH URL from GitLab to the config file it seems to switch the URL and uses the HTTP URL instead which requires a Username/Password. 

Example:
`git@gitlab.com:username/repo.git`

**Comment by chivorotkiv** [comment]
@jstnmthw

`git@....` requires a SSH key. For username/password the `https://...` URL should be used.

**Comment by jstnmthw** [comment]
Yes, I was using a key but continued to ask for a password.

**Comment by chivorotkiv** [comment]
@jstnmthw 

Git-Auto-Deploy should be able to do everything what you can do by the command line git client (actually, it uses `sh` commands). Are you able to connect your gitlab repo from your server manually by command line? Does it ask for a password?

**Comment by jstnmthw** [comment]
Ok, I got it working! It was something with the keys so I guess it reverted to asking for a password. I guess I was expecting some kind of SSH key error. 

Thanks
