### ISSUE TITLE
Cannot find "./GitAutoDeploy.py"

### ISSUE THREAD

**Issue by jstnmthw** [olipo186/Git-Auto-Deploy#65]
Seems when running the following crontab it cannot find the config file in Ubuntu 14.04
`@reboot /usr/bin/python /path/to/GitAutoDeploy.py --daemon-mode --quiet`

The Error:
```
Could not load ./GitAutoDeploy.conf.json file

Traceback (most recent call last):
  File "/path/to/GitAutoDeploy.py", line 665, in <module>
    app.run()
  File "/path/to/GitAutoDeploy.py", line 602, in run
    self.get_config()
  File "/path/to/GitAutoDeploy.py", line 410, in get_config
    raise e
IOError: [Errno 2] No such file or directory: './GitAutoDeploy.conf.json'
```

**Comment by alexandernst** [comment]
You must place the path where the config file is instead of `/path/to/GitAutoDeploy.py`...

**Comment by jstnmthw** [comment]
Ummm that was me changing my own path for the example..

**Comment by jstnmthw** [comment]
You can notice it's already being read by the fact it states specific lines and functions.

**Comment by jstnmthw** [comment]
Looks like it might have something to do with not finding the `self._config`

**Comment by jstnmthw** [comment]
Ok so, even though my GitAutoDeploy.conf.json and GitDeploy.py are in the same folder, it wouldn't find/load the config file.

I had to define the `--config` parameter in the crontab
`@reboot /usr/bin/python ~/GitDeploy/GitAutoDeploy.py --daemon-mode --quiet --config ~/GitDeploy/GitAutoDeploy.conf.json`

Now it works fine.
