### ISSUE TITLE
Deploying to multiple sites

### ISSUE THREAD

**Issue by jstnmthw** [olipo186/Git-Auto-Deploy#67]
I would like to have one server, one GitAutoDeploy script listening on one port that deploys to multiple sites (folders). The standard way of setting up a web server with multiple sites is to separate them by users. Each user has their own key, repo and folder respectively. 

To allow GitDeploy to do this, the only ways are to either. A) Set up multiple GitAutoDeploy scripts on different ports (8001, 8002, 8003), under each user, which, my guess will increase the CPU usage quite a bit? Or, B) Set up one GitDeploy user and allow access to the other users web folder, which, then the owner of the files is the GitDeploy user because he's the one doing the pulling. I would assume this is also a security risk. (Allowing one user write to multiple users documents.)

Is my thinking all wrong or is this really just designed for one website/repo/server?

**Comment by olipo186** [comment]
i agree with your two options, they are both viable. I cannot say which one is the better though, it's a matter of preference. You'll have to weigh your need of isolation between sites/projects against the benefits of controlling all repos from one instance.

I would personally actually go for option A. You could actually use the same global copy of the script, but invoke it using different users and config files (to make it easier to upgrade in the future). I like the isolation gained and being able to apply the principle of least privilege. The memory and CPU footprint of the script should be very small and I doubt it would become a problem. Although, I don't really know just how many instances we are talking about here. :)

**Comment by alexandernst** [comment]
I'd go with B with a combination of `chown/chmod`. Think about it that way. If somebody/something is so "deep" in your server to damper with GitAutoDeploy's process owner, you're already pretty much screwed. Just my 2 cents

**Comment by jstnmthw** [comment]
I actually did go with route B because having to use multiple ports listen for the same hook didn't seem to sit right with me. Although I agree with you @olipo186 on the isolation. I also initially thought `chown` would work but unless GitDeploy user is a Super User you can't change permissions to another user and I am definitely not going to give GitDeploy account `su` commands (esp. w/o requiring a password). GitDeploy will own the files but since it'll be in the same group so then the website owner user can access/edit their own files. This also means a unique group between each website user and GitDeploy will be required unless you want website user A editing website user B's content because you need to give group permission to write. 

Both seem to have their pros & cons. Do you guys host more than one site on the same machine with Git set up?

**Comment by alexandernst** [comment]
I personally do. You don't need to give GitAutoDeploy any special permissions. Just create a simple script file with `+s` attribute (setuid) that receives a path and a user/group as arguments, and performs a `chown/chmod` on that path with that user/group. Of course, make that script file writeable only by root.

Them use that script to make the folder you're deploying writeable by GitAudoDeploy, do the deploy, and then use that scripts to make the path readable/writable only by the user/group of each of your websites.

**Comment by jstnmthw** [comment]
I played around with your suggestion today and `chown` can't be used in this way. It has to be root executing the script even with setting a sticky `SETUID`.

**Comment by alexandernst** [comment]
Indeed, you're right. You can't use `setuid` on a shell script (nor a perl, python, ruby, etc... script). It must be a proper binary file. I guess you can always make a simple C app that runs your script as `root`.

```
#include <stdio.h>
#include <stdlib.h>
#include <sys/types.h>
#include <unistd.h>

int main()
{
    setuid( 0 );
    system( "/path/to/your/script.sh" );
    return 0;
 }
```

**Comment by olipo186** [comment]
I guess another way of solving this would be to have a high privileged daemon running (the core parts of GitAutoDeploy.py), which then spawns low privileges processes upon incoming requests. The repository config could then include specific UIDs for each repo.

**Comment by jstnmthw** [comment]
I just went a head with giving GitDeploy and User the same group access to the files. I figure if the user is using Git in the first place, they're not likely to be editing the files directly anyway (Even they can if they so need). Seems like the easier choice as anything else requires some major system tweaks.

Thanks for all the suggestions guys.
