### ISSUE TITLE
GitLab - push hook does not discriminate the branch

### ISSUE THREAD

**Issue by etlweather** [olipo186/Git-Auto-Deploy#74]
If I set up a repository in the configuration with a branch as in:

```
    {
      "url": "http://gitlab/playground/deploy.git",
      "branch": "master",
      "deploy": "echo deploying"
    }
```

And then I do a push of commits on the `dev` branch, a deploy is still triggered.

**Comment by etlweather** [comment]
I can modify the code and send a PR.

**Comment by olipo186** [comment]
Would be great, thank you! :)

**Comment by etlweather** [comment]
I am also adding documentation on the various aspects of the configuration file, do you want everything in one PR or multiple? Do you require squash commits or you don't care multiple commits? Just checking...

**Comment by olipo186** [comment]
I leave that for you to decide. Multiple commits are fine. Separating the docs update from the bug fix in separate PRs would maybe be a clean approach, or what do you think? Either way is fine by me, do what you think is best!

**Comment by etlweather** [comment]
Did only one PR - the docs contains so much data regarding the addition of the filtering support it was silly to separate into 2 commits.
