### ISSUE TITLE
detect branch

### ISSUE THREAD

**Issue by Quezler** [olipo186/Git-Auto-Deploy#80]
deploy script for the **master** branch runs when the webhook for **develop** gets called.

**Comment by etlweather** [comment]
Could you provide your configuration?

**Comment by Quezler** [comment]
apologies, i forgot i received the email notification.

`{
//  "pidfilepath": "/var/run/git-auto-deploy/git-auto-deploy.pid",
  "logfilepath": "/var/log/git-auto-deploy.log",
  "host": "0.0.0.0",
  "port": 8001,
  "global_deploy": [
    "echo Deploy started!",
    "echo Deploy completed!"
  ],
  "repositories": [
    {
      "url": "git@gitlab.com:Quezler/<my repo name>.git",
      "branch": "master",
      "remote": "origin",
      "path": "/webroot/public_html/<my custom web folder>.",
      "deploy": "cd /webroot/public_html/<my custom web folder> && composer install && chown -R www-data:www-data ./ && chmod -R 777 ./storage && php artisan migrate:refresh"
    }
    // {
    //   "url": "https://github.com/github/gitignore",
    //   "path": "/var/lib/git-auto-deploy/gitignore"
    // }
//  ,{
//      "url": "https://api.github.com/repos/olipo186/Git-Auto-Deploy",
//      "deploy": "echo deploying after pull request",
//      "filters": [
//        {
//          "type": "pull-request-filter",
//          "action": "closed",
//          "ref": "testing-branch"
//        }
//      ]
//    }
  ]
}`

**Comment by etlweather** [comment]
@Quezler - looks like a simple issue - I don't see any filter in your configuration. Please see: https://github.com/olipo186/Git-Auto-Deploy/blob/master/docs/Configuration.md#filters

**Comment by olipo186** [comment]
@Quezler did it work out? Please reopen the issue otherwise.
