### ISSUE TITLE
port in config is not used

### ISSUE THREAD

**Issue by pferrel** [olipo186/Git-Auto-Deploy#84]
Changing the port in config.json does not affect the deployed server. Also the default "config.json" is not
 read, you need to pass in the path on the cli.

**Comment by olipo186** [comment]
I've updated the docs to include ```--config config.json```, but also found a bug that caused some config options (port, host, pid, log) being ignored when specified in config. Fixed in https://github.com/olipo186/Git-Auto-Deploy/commit/88e25a0f6360ed8875d4ed4616518d285c05d597
