### ISSUE TITLE
Docs error?

### ISSUE THREAD

**Issue by pferrel** [olipo186/Git-Auto-Deploy#85]
https://github.com/olipo186/Git-Auto-Deploy/blob/master/docs/Configuration.md#repositories under **path**

you mean when a pull is executed, not a "clone" right?

**Comment by olipo186** [comment]
Well, both are correct. When running gitautodeploy for the first time, the value in **path** is used when doing an (initial) ```git clone <url>```. Any subsequent webhook requests will trigger a ```git pull``` (or equivalent) on the same **path**.

**Comment by pferrel** [comment]
I think my problem is that I am trying to use deploy keys, which require an ssh connection (I think) so not sure how to form the `<url>`

**Comment by olipo186** [comment]
I see, let's continue with that issue in #86. Hopefully it'll work once you use the SSH URL as URL in config.json.
