### ISSUE TITLE
Changes to run as user

### ISSUE THREAD

**Issue by pferrel** [olipo186/Git-Auto-Deploy#87]
There were several changes to run as a user other than root, these would have been much easier if the following variables and command line args had used each other. 

```
DAEMON_UID=root
DAEMON_GID=root
RUNDIR=/var/run/$NAME
PIDFILE=/var/run/$NAME.pid
PWD=/opt/Git-Auto-Deploy/
OPTIONS="--daemon-mode --quiet --pid-file /var/run/git-auto-deploy.pid --log-file /var/log/git-auto-deploy.log"
USER=root
```

For instance the  PIDFILE is not used in OPTIONS, and running as a user is a pain when forced into /var/run. Also the logfile is forced to /var/log, which is not accessible when running as a user. 

The changes I made seem to run nicely and clean up the above vars. However they may have side-effects on other systems or configs so no PR.

**Comment by olipo186** [comment]
Hi @pferrel,

Did you install the init script manually or did you use the debian package?

**Comment by pferrel** [comment]
manually, I need to run it as a user so github's ssh pull doesn't use root's public key.

**Comment by olipo186** [comment]
Hi!

When installing GAD from the debian package (apt-get install git-auto-deploy), a separate user is set up during the [installation process](https://github.com/olipo186/Git-Auto-Deploy/blob/master/platforms/debian/stdeb/git-auto-deploy.postinst) and the permissions are set accordingly for the directories you mention (/var/run/git-auto-deploy for example).

When installing the init script manually, as you have done, it will remain necessary to do these steps manually. The sample script currently has root specified as default UID, which is not a good way to run GAD. I've [updated the docs with a hint about this](https://github.com/olipo186/Git-Auto-Deploy/blob/master/docs/Start%20automatically%20on%20boot.md).

The sample init file for manual installations needed some polishing, and I've fixed the recurrence of the PID path in https://github.com/olipo186/Git-Auto-Deploy/commit/f5eb32c0887626fb4838d69099a9250094c7f422
