### ISSUE TITLE
Global Name repo_urls Not Defined

### ISSUE THREAD

**Issue by whiterook6** [olipo186/Git-Auto-Deploy#88]
We're attempting to set up GAD to work with our gitlab server. We enabled the webhook in gitlab for push events and have properly connected it to GAD. When testing the webhook or manually pushing to our dev branch, we get an error in the GAD log:

```
2016-04-12 21:02:14,722 [ERROR]  File "/usr/lib/python2.7/dist-packages/gitautodeploy/httpserver.py", line 50, in do_POST
2016-04-12 21:02:14,722 [ERROR]  File "/usr/lib/python2.7/dist-packages/gitautodeploy/httpserver.py", line 50, in do_POST
2016-04-12 21:02:14,722 [ERROR]  logger.warning('Unable to find any of the repository URLs in the config: %s' % ', '.join(repo_urls))
2016-04-12 21:02:14,722 [ERROR]  logger.warning('Unable to find any of the repository URLs in the config: %s' % ', '.join(repo_urls))
2016-04-12 21:02:14,722 [ERROR]  NameError: global name 'repo_urls' is not defined
2016-04-12 21:02:14,722 [ERROR]  NameError: global name 'repo_urls' is not defined
```

We haven't done anything unusual to our gitlab server that would cause it to submit malformed requests, I don't think.

**Comment by walkonthemarz** [comment]
I got the same problem too. My gitlab version is 8.6.1.

**Comment by olipo186** [comment]
Hi,

You've found a bug there that occurs when GAD tried to print out a specific error message. I've fixed it in master and you can grab the latest copy to get rid of the NameError exception.

I think the main problem though is something else - this error message is printed out when GAD recieved a webhook request from a repository that hasn't been configured. Have you added an entry in config.json for your repository?

If you provide a copy of your config I can have a look.

**Comment by walkonthemarz** [comment]
Here is my GAD config:
```
{
//  "pidfilepath": "/var/run/git-auto-deploy/git-auto-deploy.pid",
  "logfilepath": "/var/log/git-auto-deploy.log",
  "host": "0.0.0.0",
  "port": 8095,
  "global_deploy": [
    "echo Deploy started!",
    "echo Deploy completed!"
  ],
  "repositories": [
    {
      "url": "http://user:pass@192.168.1.106:8090/XXX/repo.git",
      "branch": "dev",
      "remote": "origin",
      "path": "/home/huyan/git-auto-deploy/rimag-web/dev",
      "deploy": "echo deploying"
    }
  ]
}
```
Thank for your help!

**Comment by olipo186** [comment]
There's currently a limitation in GAD which makes the use of https:// URLs with embedded usernames and passwords not working. I've created a separate issue for this to keep track of this as a feature request.

For now, I recommend you use the ssh:// URL and set up your gitlab repo with a deploy key, that GAD can use instead of username and password.

**Comment by olipo186** [comment]
Did it work out using the SSH URL instead? Otherwise, please reopen or make a new issue.

**Comment by walkonthemarz** [comment]
Yes, I have reinstall the latest version and it works. Thank you very much!
