### ISSUE TITLE
Makefile

### ISSUE THREAD

**Issue by alexandernst** [olipo186/Git-Auto-Deploy#9]
I'll add a Makefile to the project so users would only need to do `make install` to get everything up and running.

The Makefile should cover the following things:
- [x] Install files in the correct paths
- [x] Detect init system (initV, upstart, systemd for now)
- [ ] Install the right init script and enable it.
- [x] Update the README

**Comment by olipo186** [comment]
Hi Alex,

What is the status of this issue? There's instructions in the README. Maybe we can close this one? :)

Kind regards,
Oliver

**Comment by alexandernst** [comment]
The README is fine, but I'm not sure why the "Install the right init script and enable it" is checked. I'm having a look at the code right now and it's not doing it. Must fine some spare time and patch it.

**Comment by olipo186** [comment]
As the makefile is now mostly used for building deb packages etc instead of installing GAD, I'm closing this issue
