### ISSUE TITLE
Broken init script

### ISSUE THREAD

**Issue by skaag** [olipo186/Git-Auto-Deploy#94]
There are two issues with the init script:

1. It sends log output to console, to whoever started/restarted it first/last
2. It doesn't properly detach the process, so when you disconnect from the machine the process dies

**Comment by olipo186** [comment]
Did you install the init script manually, or are you referring to the init script included in the debian package (apt-get install git-auto-deploy)?

**Comment by olipo186** [comment]
Also, if installed manually, which init script did you use? debianLSBInitScripts or systemd? https://github.com/olipo186/Git-Auto-Deploy/tree/master/platforms/linux/initfiles

Best regards,
Oliver

**Comment by skaag** [comment]
It's the script that gets installed with the debian package from the PPA.
I will look at the init files you linked to above, and compare the differences.

I was going to just fix it today and send a merge request, but perhaps this is already fixed in one of those scripts.

I was also going to make some improvements, for example loading custom values for the init script from /etc/default/git-auto-deploy (which is how debian/ubuntu folks are used to doing things).

Thanks for a great little script by the way, we've made it part of our environment here and it works pretty nice besides the init script issue.

**Comment by olipo186** [comment]
Good catch :) I was able to reproduce the issue and fix it in f848926c0ab8b98bfd10ac6b129eed82d5531b74. The problem was that the console output was not properly suppressed when running GAD with --daemon-mode. If you fetch a new copy of GAD the issue should be resolved.

If you used the PPA to install the debian package;

    apt-get update
    apt-get upgrade git-auto-deploy

**Comment by skaag** [comment]
Thanks for fixing this so quickly. Just one last thing: It still outputs logs to console. Best if that gets sent exclusively to the log file.

**Comment by olipo186** [comment]
When using the init script bundled with the debian package, the output should (after this fix) be supressed properly by default. Are you sure you installed the updated package, and that it replaced the old init file?

    root@ubuntu:/home/oliver# service git-auto-deploy start
    Starting..
    root@ubuntu:/home/oliver#

When I try myself the output is redirected to the default log file (/var/log/git-auto-deploy.log)

    root@ubuntu:/home/oliver# tail /var/log/git-auto-deploy.log
    2016-04-28 14:28:05,798 [INFO ]  Updating /var/lib/git-auto-deploy/Git-Auto-Deploy
    2016-04-28 14:28:10,074 [INFO ]  HEAD is now at 071539f New version
    2016-04-28 14:28:10,074 [ERROR]  From https://github.com/olipo186/Git-Auto-Deploy
    2016-04-28 14:28:10,075 [ERROR]   * [new tag]         v0.2.4.1   -> v0.2.4.1
    2016-04-28 14:28:10,075 [INFO ]  Pull result: 0
    2016-04-28 14:28:10,075 [INFO ]  Executing deploy command(s)
    2016-04-28 14:28:10,078 [INFO ]  Deploy started!
    2016-04-28 14:28:10,081 [INFO ]  deploying
    2016-04-28 14:28:10,084 [INFO ]  Deploy completed!
    2016-04-28 14:28:10,085 [INFO ]  Successfully released lock: /var/lib/git-auto-deploy/Git-Auto-Deploy/status_running
    root@ubuntu:/home/oliver#

If the problem persists, please provide a copy of your ```/etc/init.d/git-auto-deploy``` init script.

**Comment by olipo186** [comment]
@skaag, I take it the issue was resolved. Please reopen or create a new issue if the problem persists.
