### ISSUE TITLE
Not working with gitlab.

### ISSUE THREAD

**Issue by No1zzz** [olipo186/Git-Auto-Deploy#95]
When i testing webhook in giltab i receive an error:
We only handle ping and push events
ip - - [29/Apr/2016 02:12:29] "POST / HTTP/1.1" 304 -

when i use gitlab test script for gitlab i receive this and working all good:
{"object_kind":"push","event_name":"push","before" <skipped> }

Push events in gitlab 
Triggered when you push to the repository except when pushing tags.
Request header:
X-Gitlab-Event: Push Hook

**Comment by DirectorX** [comment]
can you provide the whole configuration file

**Comment by olipo186** [comment]
Hi,

What version of GitLab are you running?

BR,
Oliver

**Comment by olipo186** [comment]
@No1zzz, please get back to me with a copy of your configuration and a copy of the console output (or logfile) from GAD.

You can also try upgradring to the latest version. If you installed using the debian package;

    apt-get update
    apt-get upgrade git-auto-deploy

**Comment by olipo186** [comment]
@No1zzz; If the problem persists, create a new issue or reopen this one.
