### ISSUE TITLE
feature: Protect web server with a token in the url

### ISSUE THREAD

**Issue by danieljuhl** [olipo186/Git-Auto-Deploy#96]
I made a modification to the script, which protects the webhook service. What it does, is that in the config, a key is defined, and then the url to be hit is now `....:8001/$key`. It would then be harder to trigger the git-auto-deploy service.

Is it something you would accept if I made a PR?

**Comment by DirectorX** [comment]
Can you provide a link to your modified code?

**Comment by olipo186** [comment]
There's a nice feature in GitHub that provides similar (but better) security; https://developer.github.com/webhooks/securing. I added support for it in 717d7478584c948eb6fd5c6b51f094d8ae6a99fd. Only problem is, it's limited to GitHub. Bitbucket, GitLab and other services doesn't seem to have any similar support.

**Comment by olipo186** [comment]
Since this issue was created, GitLab has introduced support for secret tokens. I'm closing this issue since it's a redundant feature.

**Comment by danieljuhl** [comment]
Great... I'll test it asap.
