### ISSUE TITLE
Unable to find any repository URLs in the config

### ISSUE THREAD

**Issue by 3x1l3** [olipo186/Git-Auto-Deploy#97]
I'm getting a warning in my /var/log/git-auto-deploy.log file:

> 2016-05-09 13:05:49,538 [INFO ]  Received event from GitLab
2016-05-09 13:05:49,541 [INFO ]  192.168.0.140 - - [09/May/2016 13:05:49] "POST / HTTP/1.1" 200 -

>2016-05-09 13:05:49,542 [INFO ]  Received 'Push Hook' event from GitLab
2016-05-09 13:05:49,542 [INFO ]  Event details - ref: refs/heads/master; action: push
2016-05-09 13:05:49,542 [WARNI]  Unable to find any of the repository URLs in the config: git@192.168.0.140:exile/test.git, http://192.168.0.140/exile/test.git, git@192.168.0.140:exile/test.git

The Git URL is listed in my config file as follows:
>{
  "pidfilepath": "~/.gitautodeploy.pid",
  "logfilepath": "~/gitautodeploy.log",
  "host": "0.0.0.0",
  "port": 8001,
  "global_deploy": [
    "echo Deploy started!",
    "echo Deploy completed!"
  ],
  "repositories": [
    {
      "url": "http://192.168.0.140/exile/test.git",
      "deploy": "echo deploying after pull request",
      "filters": [
        {
          "object_kind": "push",
          "ref": "refs/heads/master"
        }
      ]
    }
  ]
}

GitLab is hosted on the same server as Git-Auto-Deploy. I'm running it on Ubuntu 16.04 and I installed Git-Auto-Deploy from the debian repos, not manually from Git.

**Comment by olipo186** [comment]
Hi,

Is that an identical copy of your config? GAD should have recognized http://192.168.0.140/exile/test.git as it matches the entry in the config you provided.

Did you restart GAD after making your config edits?

    service git-auto-deploy restart

Also, there's a new version in the apt repository since yesterday, so you could also try.

    apt-get update
    apt-get upgrade git-auto-deploy

**Comment by 3x1l3** [comment]
Ok Thanks! It seems to be working for some reason now. I thought I restarted the service every time. I left it for a few hours and it started working. Thanks for the reply.
