### ISSUE TITLE
Global deploy configuration problem

### ISSUE THREAD

**Issue by nomysz** [olipo186/Git-Auto-Deploy#98]
I have experiendced some troubles with global deploy. My config:

> 
{
        "pidfilepath": "~/.gitautodeploy.pid",
        "host": "0.0.0.0",
        "port": 8001,
        "global_deploy": [
                "echo Deploy triggerd `date +'%d-%m-%Y %H:%M:%S'` >> /home/www/log/autodeploy.log"
        ],
        "repositories":
        [
                {
                        "url": "http://myrepo1......git",
                        "branch": "production",
                        "remote": "origin",
                        "path": "/home/www/mypath1",
                        "deploy": "composer install && composer dump-autoload --optimize"
                },
                {
                        "url": "http://myrepo1......git",
                        "branch": "production",
                        "remote": "origin",
                        "path": "/home/www/mypath2",
                        "deploy": "composer install && composer dump-autoload --optimize"
                }
        ]
}

I got error when starting deamon

> 
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/www/.../gitautodeploy/__main__.py", line 5, in <module>
    main()
  File "gitautodeploy/gitautodeploy.py", line 447, in main
    init_config(config)
  File "gitautodeploy/cli/config.py", line 265, in init_config
    if 'global_deploy' in config and len(config['global_deploy'][1]) is not 0:
IndexError: list index out of range

Its probably bug in parsing global deploy config

**Comment by olipo186** [comment]
Hi! The issue should be resolved now. Please grab the latest copy and try.

**Comment by nomysz** [comment]
Worked like charm.
Thanks
